export enum PaylistEnum {
  KAKAOPAY = 'kakaopay',
  NAVERPAY = 'naverpay',
  PAYCO = 'payco',
  ZEROPAY = 'zeropay',
  APPLE_VISA = 'apple_visa',
  APPLE_MASTER = 'apple_master',
  APPLE_JCB = 'apple_jcb',
  CONLESS_VISA = 'conless_visa',
  CONLESS_MASTER = 'conless_master',
  CONLESS_AMEX = 'conless_amex',
  CONLESS_UNION = 'conless_union',
  CONLESS_JCB = 'conless_jcb',
  GOOGLE_VISA = 'google_visa',
  GOOGLE_MASTER = 'google_master',
  GOOGLE_MAESTRO = 'google_maestro',
}
